### ISSUE TITLE
Capabilities

### ISSUE THREAD

**Issue by 6ffm70** [BortEngineerDude/sw6106mon#1]
@BortEngineerDude this looks interesting! What capabilities does it have? What can we read with that on the SW6106? 
Can you add an example output to `README.md`?

**Comment by BortEngineerDude** [comment]
Right now, it is capable of reading:

- Charge/Discharge current
- Battery voltage
- Output voltage
- Estimated (by sw6106) battery charge percent
- Device state, i.e. Charger connected, Port A connected
- In service mode only: events, such as Micro USB charger connected, Type C load disconnected, Battery Overvoltage and so on

Expanded README.md with sample output in single-run mode.

**Comment by 6ffm70** [comment]
Awesome. I like the soldering advice too!
